using UnityEngine;

public enum Books
{
    Genesis,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    _1Samuel,
    _2Samuel,
    _1_Kings,
    _2_Kings,
    _1_Chronicles,
    _2_Chronicles,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalms,
    Proverbs,
    Ecclesiastes,
    Song_of_Solomon,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    _1_Corinthians,
    _2_Corinthians,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    _1_Thessalonians,
    _2_Thessalonian,
    _1_Timothy,
    _2_Timothy,
    Titus,
    Philemon,
    Hebrews,
    James,
    _1_Peter,
    _2_Peter,
    _1_John,
    _2_John,
    _3_John,
    Jude,
    Revelation
}

public static class BookFinder
{
    public static string Find(Books book)
    {
        return book switch
        {
            Books.Genesis => "GEN",
            Books.Exodus => "EXO",
            Books.Leviticus => "LEV",
            Books.Numbers => "NUM",
            Books.Deuteronomy => "DEU",
            Books.Joshua => "JOS",
            Books.Judges => "JDG",
            Books.Ruth => "RUT",
            Books._1Samuel => "1SA",
            Books._2Samuel => "2SA",
            Books._1_Kings => "1KI",
            Books._2_Kings => "2KI",
            Books._1_Chronicles => "1CH",
            Books._2_Chronicles => "2CH",
            Books.Ezra => "EZR",
            Books.Nehemiah => "NEH",
            Books.Esther => "EST",
            Books.Job => "JOB",
            Books.Psalms => "PSA",
            Books.Proverbs => "PRO",
            Books.Ecclesiastes => "ECC",
            Books.Song_of_Solomon => "SNG",
            Books.Isaiah => "ISA",
            Books.Jeremiah => "JER",
            Books.Lamentations => "LAM",
            Books.Ezekiel => "EZK",
            Books.Daniel => "DAN",
            Books.Hosea => "HOS",
            Books.Joel => "JOL",
            Books.Amos => "AMO",
            Books.Obadiah => "OBA",
            Books.Jonah => "JON",
            Books.Micah => "MIC",
            Books.Nahum => "NAM",
            Books.Habakkuk => "HAB",
            Books.Zephaniah => "ZEP",
            Books.Haggai => "HAG",
            Books.Zechariah => "ZEC",
            Books.Malachi => "MAL",
            Books.Matthew => "MAT",
            Books.Mark => "MRK",
            Books.Luke => "LUK",
            Books.John => "JHN",
            Books.Acts => "ACT",
            Books.Romans => "ROM",
            Books._1_Corinthians => "1CO",
            Books._2_Corinthians => "2CO",
            Books.Galatians => "GAL",
            Books.Ephesians => "EPH",
            Books.Philippians => "PHP",
            Books.Colossians => "COL",
            Books._1_Thessalonians => "1TH",
            Books._2_Thessalonian => "2TH",
            Books._1_Timothy => "1TI",
            Books._2_Timothy => "2TI",
            Books.Titus => "TIT",
            Books.Philemon => "PHM",
            Books.Hebrews => "HEB",
            Books.James => "JAS",
            Books._1_Peter => "1PE",
            Books._2_Peter => "2PE",
            Books._1_John => "1JN",
            Books._2_John => "2JN",
            Books._3_John => "3JN",
            Books.Jude => "JUD",
            Books.Revelation => "REV",
            _ => string.Empty
        };
    }
}
